"""Read an FFR seed's flag set straight out of the cartridge.

FF1Rom.WriteSeedAndFlags stamps a plain-ASCII record into bank 0x1E at 0xBE00 --
file offset 0x7BE10 once the 16-byte iNES header is counted:

    FFRInfo|Seed: D0E0CDBF|OW Seed: none|Res. Pack Hash: none|Flags: g5jr...|Version: 4-9-7

The flag string is one BigInteger written in FFR's own base-64 alphabet, least
significant digit first. Decoding is repeated divmod: one division per Flags
property, taken in reverse-alphabetical order of property name, by that
property's radix (3 for a tri-state, 2 for a bool, max+1 for an enum, the step
count for an int or a double). The build SHA that FF1Lib mixed in first comes
out last, which is what makes a wrong schema detectable rather than silent.

The property order and radixes are version-specific; schemas/ holds one JSON per
FFR version, generated by dump_schema/ against the matching FF1Lib checkout.
"""

import json
import os
import re

B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.-"

# FF1Lib computes this as Math.Pow(0xFF, 7) - 1 in double precision and then
# truncates to a BigInteger, so it is the nearest double to 255**7, not 255**7-1.
SHA_DIVISOR = int(float(255 ** 7 - 1))

ROM_HEADER = 16
FLAGS_ROM_OFFSET = 0x7BE00          # PRG offset; add ROM_HEADER for a file offset
INFO_MARKER = b"FFRInfo"

SCHEMA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "schemas")


class DecodeError(Exception):
    pass


def read_info(rom_bytes):
    """The FFRInfo record as a dict, or None if this is not an FFR ROM.

    Looks at the documented offset first and falls back to a scan, so a build
    that moved the record still reads.
    """
    at = FLAGS_ROM_OFFSET + ROM_HEADER
    if rom_bytes[at:at + len(INFO_MARKER)] != INFO_MARKER:
        at = rom_bytes.find(INFO_MARKER)
        if at < 0:
            return None
    raw = rom_bytes[at:at + 1024].split(b"\x00")[0].decode("ascii", "replace")
    info = {}
    for part in raw.split("|")[1:]:
        if ": " in part:
            key, value = part.split(": ", 1)
            info[key] = value
    info["_offset"] = at
    return info


def load_schema(version):
    """Schema for an FFR version string as the ROM writes it, e.g. "4-9-7"."""
    path = os.path.join(SCHEMA_DIR, version + ".json")
    if not os.path.exists(path):
        return None
    with open(path) as handle:
        return json.load(handle)


def decode(flagstring, schema):
    """{property: value} for every encoded flag, or raise DecodeError.

    Raises when the trailing build SHA does not match the schema's, which is the
    only way to tell a schema from the wrong FFR version apart from a good one.
    """
    for char in flagstring:
        if char not in B64:
            raise DecodeError("%r is not FFR-style base64" % char)

    total = 0
    for char in reversed(flagstring):
        total = total * 64 + B64.index(char)

    values = {}
    for entry in schema["properties"]:
        total, raw = divmod(total, entry["radix"])
        kind = entry["kind"]
        if kind == "tristate":
            values[entry["name"]] = (False, True, None)[raw]
        elif kind == "bool":
            values[entry["name"]] = raw != 0
        elif kind == "enum":
            values[entry["name"]] = raw
        elif kind in ("int", "double"):
            values[entry["name"]] = raw * entry["step"] + entry["min"]
        else:
            raise DecodeError("unknown kind %r for %s" % (kind, entry["name"]))

    total, raw = divmod(total, SHA_DIVISOR)
    sha = raw.to_bytes((raw.bit_length() + 8) // 8 or 1, "little")
    sha = sha.rstrip(b"\x00").decode("ascii", "replace")
    if sha != schema["build_sha"]:
        raise DecodeError("build sha %r does not match schema %r for FFR %s"
                          % (sha, schema["build_sha"], schema["version"]))
    if total != 0:
        raise DecodeError("%d left over after decoding -- schema is wrong" % total)
    return values


def decode_rom(rom_bytes):
    """(info, flags) for an FFR ROM. Raises DecodeError with a plain reason."""
    info = read_info(rom_bytes)
    if info is None:
        raise DecodeError("no FFRInfo record -- not an FFR ROM, or too old a build")
    if "Flags" not in info or "Version" not in info:
        raise DecodeError("FFRInfo record has no Flags/Version field")
    schema = load_schema(info["Version"])
    if schema is None:
        raise DecodeError("no schema for FFR %s (see tools/ffr_flags/README.md)"
                          % info["Version"])
    return info, decode(info["Flags"], schema)


def permalink_flags(text):
    """The f= value out of an FFR permalink, or the text itself if it is bare."""
    match = re.search(r"[?&]f=([A-Za-z0-9.\-]+)", text)
    return match.group(1) if match else text
