#!/usr/bin/env python3
"""Generate the flag schema for one FFR version, and prove it on a real ROM.

    python3 tools/ffr_flags/gen_schema.py --ff1lib ~/src/FF1Randomizer/FF1Lib \
        --rom "~/Library/Application Support/Archipelago/output/FFR_D0E0CDBF_TFXhhTGS.nes"

Needs the .NET SDK and a checkout of FiendsOfTheElements/FF1Randomizer at the
tag or branch that built the ROM (master is the released version; dev is ahead).

The build SHA comes from the checkout's git HEAD -- FFRVersion.Sha is a
placeholder in source and only gets substituted during FFR's own build. The ROM
decode then has to end on that same SHA with nothing left over, which is what
says the property order and radixes are right rather than merely plausible.

Writes tools/ffr_flags/schemas/<version>.json for the offline tools and
scripts/flags/schema_<version>.lua for the pack.
"""

import argparse
import json
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ffr_flags  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
PACK_ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))


def run_dumper(ff1lib):
    proc = subprocess.run(
        ["dotnet", "run", "--project", os.path.join(HERE, "dump_schema"),
         "-c", "Release", "-p:FF1LibPath=" + ff1lib],
        capture_output=True, text=True,
    )
    sys.stderr.write(proc.stderr)
    if proc.returncode != 0:
        raise SystemExit("dump_schema failed")
    return json.loads(proc.stdout)


def stamped_sha(checkout):
    """The SHA hardcoded into FFRVersion.cs, or None if it is still upstream's.

    FFR substitutes `Sha` during its own deploy and leaves the literal "SHA" in
    source, so a locally built oracle cartridge has to stamp it by hand or the
    flag decoder refuses the ROM. That stamp is what the cartridge carries, so
    it is what the schema has to record -- see the comment in git_sha.
    """
    src = os.path.join(checkout, "FF1Lib", "FFRVersion.cs")
    if not os.path.isfile(src):
        return None
    with open(src, encoding="utf-8", errors="replace") as handle:
        m = re.search(r'\bSha\s*=\s*"([^"]+)"', handle.read())
    if not m or m.group(1) == "SHA":
        return None
    return m.group(1)


def git_sha(checkout):
    """The build SHA to record: the stamp if there is one, else HEAD.

    HEAD alone was wrong, and quietly so. Both oracle worktrees sit two local
    commits above the release they are checked out at -- the FF1R export commit
    and the FFRVersion stamp -- so HEAD is not the commit the cartridges claim.
    Regenerating 4-9-7 from the pinned worktree wrote `b4ec325` where the ROMs
    say `1f31434`, and the proof loop below then failed against every oracle
    cartridge that exists. Loud rather than silent, but the failure was in the
    checker rather than in the tree, which is the worst place for it.

    The stamp is the right source because it is what ends up in the ROM, which
    is the value ffr_flags.py:102 compares the schema against.
    """
    stamped = stamped_sha(checkout)
    if stamped:
        return stamped
    proc = subprocess.run(["git", "-C", checkout, "rev-parse", "HEAD"],
                          capture_output=True, text=True)
    if proc.returncode != 0:
        raise SystemExit("not a git checkout: " + checkout)
    return proc.stdout.strip()[:7]


def lua_str(text):
    return json.dumps(text)


def to_lua(schema):
    """The schema as a Lua chunk that registers itself in FFR_FLAG_SCHEMAS.

    Assignment rather than `return`, because PopTracker packs load scripts
    through ScriptHost:LoadScript, which does not hand a value back.

    Radixes are what the decode needs; the names ride along so the mapping in
    scripts/autotracking/flag_mapping.lua can be written against FFR's own
    vocabulary instead of against positions in this list.
    """
    lines = [
        "-- Generated by tools/ffr_flags/gen_schema.py. Do not edit by hand.",
        "--",
        "-- The Flags property order and radixes for one FFR version, in decode",
        "-- order (reverse alphabetical by property name). build_sha is what the",
        "-- trailing seven characters of a flag string have to come out as; a",
        "-- mismatch means this schema belongs to a different FFR build.",
        "",
        "FFR_FLAG_SCHEMAS = FFR_FLAG_SCHEMAS or {}",
        "FFR_FLAG_SCHEMAS[%s] = {" % lua_str(schema["version"]),
        "  version = %s," % lua_str(schema["version"]),
        "  build_sha = %s," % lua_str(schema["build_sha"]),
        "  properties = {",
    ]
    for entry in schema["properties"]:
        parts = ["name=%s" % lua_str(entry["name"]),
                 "kind=%s" % lua_str(entry["kind"]),
                 "radix=%d" % entry["radix"]]
        if entry["kind"] in ("int", "double"):
            parts.append("min=%r" % entry["min"])
            parts.append("step=%r" % entry["step"])
        lines.append("    {" + ", ".join(parts) + "},")
    lines.append("  },")
    lines.append("}")
    return "\n".join(lines) + "\n"


def write_index(flags_dir):
    """scripts/flags/schemas.lua -- loads every schema in the directory.

    Generated so that adding a version is one gen_schema.py run and not also an
    edit to init.lua that is easy to forget.
    """
    names = sorted(f for f in os.listdir(flags_dir)
                   if f.startswith("schema_") and f.endswith(".lua"))
    lines = [
        "-- Generated by tools/ffr_flags/gen_schema.py. Do not edit by hand.",
        "--",
        "-- Every FFR version whose flag encoding this pack knows. A seed built",
        "-- by a version that is not here keeps the manual flag grid.",
        "",
    ]
    for name in names:
        lines.append('ScriptHost:LoadScript("scripts/flags/%s")' % name)
    path = os.path.join(flags_dir, "schemas.lua")
    with open(path, "w") as handle:
        handle.write("\n".join(lines) + "\n")
    return path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ff1lib", required=True,
                    help="FF1Lib directory inside an FF1Randomizer checkout")
    ap.add_argument("--rom", required=True, action="append",
                    help="an FFR ROM built by that version, to prove the schema")
    args = ap.parse_args()

    ff1lib = os.path.abspath(os.path.expanduser(args.ff1lib))
    schema = run_dumper(ff1lib)
    schema["build_sha"] = git_sha(os.path.dirname(ff1lib.rstrip("/")))
    print("build sha from checkout: %s" % schema["build_sha"])

    for rom_path in args.rom:
        with open(os.path.expanduser(rom_path), "rb") as handle:
            rom = handle.read()
        info = ffr_flags.read_info(rom)
        if info is None:
            raise SystemExit("no FFRInfo in " + rom_path)
        if info["Version"] != schema["version"]:
            raise SystemExit("%s is FFR %s, schema is %s"
                             % (rom_path, info["Version"], schema["version"]))
        ffr_flags.decode(info["Flags"], schema)   # raises unless it checks out
        print("verified against %s (seed %s)"
              % (os.path.basename(rom_path), info["Seed"]))

    json_path = os.path.join(HERE, "schemas", schema["version"] + ".json")
    with open(json_path, "w") as handle:
        json.dump(schema, handle, indent=1)
        handle.write("\n")
    lua_path = os.path.join(PACK_ROOT, "scripts", "flags",
                            "schema_" + schema["version"] + ".lua")
    with open(lua_path, "w") as handle:
        handle.write(to_lua(schema))
    index_path = write_index(os.path.dirname(lua_path))
    for path in (json_path, lua_path, index_path):
        print("wrote %s" % os.path.relpath(path, PACK_ROOT))


if __name__ == "__main__":
    main()
