-- Generated by tools/incentive_slots.py. Do not edit by hand.
--
-- Every section a seed's incentive flags speak for, and the flags that
-- speak for it. scripts/incentives.lua rings the ones a seed kept.
--
-- `flags` is an AND: FFR computes two of these conditions as
-- conjunctions rather than storing them (FlagsCompute.cs:217, :220-226),
-- so a slot can answer to more than one flag and rings only on all of
-- them.
--
-- Both incentive trees are listed and only one loads per variant, so a
-- path that does not resolve is expected rather than an error.
--
-- `standardOnly` is FFR's third term on IncentivizeNerrick
-- (FlagsCompute.cs:224, `&& !NoOverworld`). It sits on a board row
-- because both variants load the same board tree, so the file cannot
-- say it and the row has to.
--
-- `hosted` is the section's hosted item code, which is also what
-- LOCATION_MAPPING carries beside each Archipelago location id. It is
-- how a ring asks whether this seed has the location at all: the flags
-- can say a slot is incentivized on a seed that does not contain it.
INCENTIVE_SLOTS = {
  { flags = { "coneriaLockedIsIncentive" },                  hosted = "coneriaLocked",    path = "@I: Coneria Castle/I: Coneria Castle Incentive" },
  { flags = { "npcItems", "npcsAreIncentive" },              hosted = "king",             path = "@I: Coneria Castle/I: King" },
  { flags = { "npcItems", "npcsAreIncentive" },              hosted = "sara",             path = "@I: Coneria Castle/I: Sara" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  hosted = "smith",            path = "@I: Dwarf Cave/I: Smithy McBeardSmith" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  hosted = "nerrick",          path = "@I: Dwarf Cave/I: Nerrick (Vanilla Canal)" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  hosted = "astos",            path = "@I: North West Castle/I: Astos" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  hosted = "matoya",           path = "@I: Matoya's Cave/I: Matoya" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  hosted = "elfprince",        path = "@I: Elf Castle/I: Elf Prince" },
  { flags = { "npcItems", "npcsAreIncentive" },              hosted = "bikke",            path = "@I: Pravoka/I: Bikke" },
  { flags = { "marshIsIncentive" },                          hosted = "marsh",            path = "@I: Marsh Cave/I: Marsh Incentive" },
  { flags = { "marshLockedIsIncentive" },                    hosted = "marshLocked",      path = "@I: Marsh Cave/I: Marsh Locked Incentive" },
  { flags = { "npcItems", "npcsAreIncentive" },              hosted = "sarda",            path = "@I: Sarda's Cave/I: Sarda" },
  { flags = { "titansTroveIsIncentive" },                    hosted = "titansTrove",      path = "@I: Titan's Trove/I: Incentive" },
  { flags = { "earthIsIncentive" },                          hosted = "earth",            path = "@I: Earth Cave/I: Earth Incentive" },
  { flags = { "npcItems", "npcsAreIncentive" },              hosted = "sages",            path = "@I: Crescent Lake/I: Sages" },
  { flags = { "iceCaveIsIncentive" },                        hosted = "iceCave",          path = "@I: Ice Cave/I: Ice Cave Incentive" },
  { flags = { "volcanoIsIncentive" },                        hosted = "volcano",          path = "@I: Volcano/I: Volcano Incentive" },
  { flags = { "cardiaIsIncentive" },                         hosted = "cardiaIncentive",  path = "@I: Bahamut's Cave/I: Cardia Incentive" },
  { flags = { "cardiaIsIncentive" },                         hosted = "cardiaIncentive",  path = "@I: Cardia Incentive/I: Cardia Incentive" },
  { flags = { "ordealsIsIncentive" },                        hosted = "ordeals",          path = "@I: Ordeals/I: Incentive" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  hosted = "lefein",           path = "@I: Lefein/I: Incentive" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  hosted = "fairy",            path = "@I: Gaia/I: Fairy" },
  { flags = { "skyIsIncentive" },                            hosted = "sky",              path = "@I: Sky Palace/I: Sky Incentive" },
  { flags = { "npcItems", "npcsAreIncentive" },              hosted = "robot",            path = "@I: Waterfall/I: Robot" },
  { flags = { "seaIsIncentive" },                            hosted = "sea",              path = "@I: Sea Shrine/I: Sea Incentive" },
  { flags = { "npcItems", "npcsAreIncentive" },              hosted = "shopItem",         path = "@I: Shop Item/I: Shop Item" },
  { flags = { "coneriaLockedIsIncentive" },                  hosted = "coneriaLocked",    path = "@I: Coneria Castle Locked/I: Coneria Castle Incentive" },
  { flags = { "cardiaIsIncentive" },                         hosted = "cardiaIncentive",  path = "@I: Bahamut/I: Cardia Incentive" },
  { flags = { "seaIsIncentive" },                            hosted = "sea",              path = "@I: Sea Incentive/I: Sea Incentive" },
  { flags = { "npcItems", "npcsAreIncentive" },              hosted = "king",             path = "@Coneria Castle King/King" },
  { flags = { "npcItems", "npcsAreIncentive" },              hosted = "sara",             path = "@Coneria Castle Sara/Sara" },
  { flags = { "coneriaLockedIsIncentive" },                  hosted = "coneriaLocked",    path = "@Coneria Castle Incentive/Incentive" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  hosted = "smith",            path = "@Dwarf Cave Smith/Smithy McBeardSmith" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  hosted = "nerrick",          path = "@Dwarf Cave Nerrick/Nerrick (Vanilla Canal)", standardOnly = true },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  hosted = "astos",            path = "@North West Castle Astos/Astos" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  hosted = "matoya",           path = "@Matoya's Cave Matoya/Matoya" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  hosted = "elfprince",        path = "@Elf Castle Elf Prince/Elf Prince" },
  { flags = { "npcItems", "npcsAreIncentive" },              hosted = "bikke",            path = "@Pravoka/Bikke" },
  { flags = { "marshIsIncentive" },                          hosted = "marsh",            path = "@Marsh Cave Marsh Incentive/Incentive" },
  { flags = { "marshLockedIsIncentive" },                    hosted = "marshLocked",      path = "@Marsh Cave Marsh Locked Incentive/Incentive" },
  { flags = { "npcItems", "npcsAreIncentive" },              hosted = "sarda",            path = "@Sarda's Cave/Sarda" },
  { flags = { "titansTroveIsIncentive" },                    hosted = "titansTrove",      path = "@Titan's Trove Incentive/Incentive" },
  { flags = { "earthIsIncentive" },                          hosted = "earth",            path = "@Earth Cave Earth Incentive/Incentive" },
  { flags = { "npcItems", "npcsAreIncentive" },              hosted = "sages",            path = "@Crescent Lake/Sages" },
  { flags = { "iceCaveIsIncentive" },                        hosted = "iceCave",          path = "@Ice Cave Incentive/Incentive" },
  { flags = { "volcanoIsIncentive" },                        hosted = "volcano",          path = "@Volcano Incentive/Incentive" },
  { flags = { "cardiaIsIncentive" },                         hosted = "cardiaIncentive",  path = "@Bahamut's Cave/Cardia Incentive - Hoard" },
  { flags = { "cardiaIsIncentive" },                         hosted = "cardiaIncentive",  path = "@Cardia Forest Incentive/Incentive" },
  { flags = { "ordealsIsIncentive" },                        hosted = "ordeals",          path = "@Ordeals Incentive/Incentive" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  hosted = "lefein",           path = "@Lefein/Incentive" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  hosted = "fairy",            path = "@Gaia/Fairy" },
  { flags = { "skyIsIncentive" },                            hosted = "sky",              path = "@Sky Palace Sky Incentive/Incentive" },
  { flags = { "npcItems", "npcsAreIncentive" },              hosted = "robot",            path = "@Waterfall Robot/Robot" },
  { flags = { "seaIsIncentive" },                            hosted = "sea",              path = "@Sea Shrine Sea Incentive/Incentive" },
}
