-- Generated by tools/incentive_slots.py. Do not edit by hand.
--
-- Every section a seed's incentive flags speak for, and the flags that
-- speak for it. scripts/incentives.lua rings the ones a seed kept.
--
-- `flags` is an AND: FFR computes two of these conditions as
-- conjunctions rather than storing them (FlagsCompute.cs:217, :220-226),
-- so a slot can answer to more than one flag and rings only on all of
-- them.
--
-- Both incentive trees are listed and only one loads per variant, so a
-- path that does not resolve is expected rather than an error.
--
-- `standardOnly` is FFR's third term on IncentivizeNerrick
-- (FlagsCompute.cs:224, `&& !NoOverworld`). It sits on a board row
-- because both variants load the same board tree, so the file cannot
-- say it and the row has to.
INCENTIVE_SLOTS = {
  { flags = { "coneriaLockedIsIncentive" },                  path = "@I: Coneria Castle/I: Coneria Castle Incentive" },
  { flags = { "npcItems", "npcsAreIncentive" },              path = "@I: Coneria Castle/I: King" },
  { flags = { "npcItems", "npcsAreIncentive" },              path = "@I: Coneria Castle/I: Sara" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  path = "@I: Dwarf Cave/I: Smithy McBeardSmith" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  path = "@I: Dwarf Cave/I: Nerrick (Vanilla Canal)" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  path = "@I: North West Castle/I: Astos" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  path = "@I: Matoya's Cave/I: Matoya" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  path = "@I: Elf Castle/I: Elf Prince" },
  { flags = { "npcItems", "npcsAreIncentive" },              path = "@I: Pravoka/I: Bikke" },
  { flags = { "marshIsIncentive" },                          path = "@I: Marsh Cave/I: Marsh Incentive" },
  { flags = { "marshLockedIsIncentive" },                    path = "@I: Marsh Cave/I: Marsh Locked Incentive" },
  { flags = { "npcItems", "npcsAreIncentive" },              path = "@I: Sarda's Cave/I: Sarda" },
  { flags = { "titansTroveIsIncentive" },                    path = "@I: Titan's Trove/I: Incentive" },
  { flags = { "earthIsIncentive" },                          path = "@I: Earth Cave/I: Earth Incentive" },
  { flags = { "npcItems", "npcsAreIncentive" },              path = "@I: Crescent Lake/I: Sages" },
  { flags = { "iceCaveIsIncentive" },                        path = "@I: Ice Cave/I: Ice Cave Incentive" },
  { flags = { "volcanoIsIncentive" },                        path = "@I: Volcano/I: Volcano Incentive" },
  { flags = { "cardiaIsIncentive" },                         path = "@I: Bahamut's Cave/I: Cardia Incentive" },
  { flags = { "cardiaIsIncentive" },                         path = "@I: Cardia Incentive/I: Cardia Incentive" },
  { flags = { "ordealsIsIncentive" },                        path = "@I: Ordeals/I: Incentive" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  path = "@I: Lefein/I: Incentive" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  path = "@I: Gaia/I: Fairy" },
  { flags = { "skyIsIncentive" },                            path = "@I: Sky Palace/I: Sky Incentive" },
  { flags = { "npcItems", "npcsAreIncentive" },              path = "@I: Waterfall/I: Robot" },
  { flags = { "seaIsIncentive" },                            path = "@I: Sea Shrine/I: Sea Incentive" },
  { flags = { "npcItems", "npcsAreIncentive" },              path = "@I: Shop Item/I: Shop Item" },
  { flags = { "coneriaLockedIsIncentive" },                  path = "@I: Coneria Castle Locked/I: Coneria Castle Incentive" },
  { flags = { "cardiaIsIncentive" },                         path = "@I: Bahamut/I: Cardia Incentive" },
  { flags = { "seaIsIncentive" },                            path = "@I: Sea Incentive/I: Sea Incentive" },
  { flags = { "npcItems", "npcsAreIncentive" },              path = "@Coneria Castle King/King" },
  { flags = { "npcItems", "npcsAreIncentive" },              path = "@Coneria Castle Sara/Sara" },
  { flags = { "coneriaLockedIsIncentive" },                  path = "@Coneria Castle Incentive/Incentive" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  path = "@Dwarf Cave Smith/Smithy McBeardSmith" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  path = "@Dwarf Cave Nerrick/Nerrick (Vanilla Canal)", standardOnly = true },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  path = "@North West Castle Astos/Astos" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  path = "@Matoya's Cave Matoya/Matoya" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  path = "@Elf Castle Elf Prince/Elf Prince" },
  { flags = { "npcItems", "npcsAreIncentive" },              path = "@Pravoka/Bikke" },
  { flags = { "marshIsIncentive" },                          path = "@Marsh Cave Marsh Incentive/Incentive" },
  { flags = { "marshLockedIsIncentive" },                    path = "@Marsh Cave Marsh Locked Incentive/Incentive" },
  { flags = { "npcItems", "npcsAreIncentive" },              path = "@Sarda's Cave/Sarda" },
  { flags = { "titansTroveIsIncentive" },                    path = "@Titan's Trove Incentive/Incentive" },
  { flags = { "earthIsIncentive" },                          path = "@Earth Cave Earth Incentive/Incentive" },
  { flags = { "npcItems", "npcsAreIncentive" },              path = "@Crescent Lake/Sages" },
  { flags = { "iceCaveIsIncentive" },                        path = "@Ice Cave Incentive/Incentive" },
  { flags = { "volcanoIsIncentive" },                        path = "@Volcano Incentive/Incentive" },
  { flags = { "cardiaIsIncentive" },                         path = "@Bahamut's Cave/Cardia Incentive - Hoard" },
  { flags = { "cardiaIsIncentive" },                         path = "@Cardia Forest Incentive/Incentive" },
  { flags = { "ordealsIsIncentive" },                        path = "@Ordeals Incentive/Incentive" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  path = "@Lefein/Incentive" },
  { flags = { "fetchQuestsAreIncentive", "npcFetchItems" },  path = "@Gaia/Fairy" },
  { flags = { "skyIsIncentive" },                            path = "@Sky Palace Sky Incentive/Incentive" },
  { flags = { "npcItems", "npcsAreIncentive" },              path = "@Waterfall Robot/Robot" },
  { flags = { "seaIsIncentive" },                            path = "@Sea Shrine Sea Incentive/Incentive" },
}
