-- Map id -> the name this pack shows for it.
--
-- Committed rather than written by a regen, unlike its neighbour
-- entrance_links.lua, because it is not a fact about a seed: FFR
-- shuffles which map a door leads to and never renames a map. The list
-- is tools/entrance_graph.MAP_NAMES, and
-- tools/tests/test_map_names.py fails when the two drift.
--
-- -1 is the overworld, the same value ff1/map and ff1/edges use.
MAP_NAMES = {
  [-1] = "Overworld",
  [0] = "ConeriaTown",
  [1] = "Pravoka",
  [2] = "Elfland",
  [3] = "Melmond",
  [4] = "CrescentLake",
  [5] = "Gaia",
  [6] = "Onrac",
  [7] = "Lefein",
  [8] = "ConeriaCastle1F",
  [9] = "ElflandCastle",
  [10] = "NorthwestCastle",
  [11] = "CastleOrdeals1F",
  [12] = "TempleOfFiends",
  [13] = "EarthCaveB1",
  [14] = "GurguVolcanoB1",
  [15] = "IceCaveB1",
  [16] = "Cardia",
  [17] = "BahamutCaveB1",
  [18] = "Waterfall",
  [19] = "DwarfCave",
  [20] = "MatoyasCave",
  [21] = "SardasCave",
  [22] = "MarshCaveB1",
  [23] = "MirageTower1F",
  [24] = "ConeriaCastle2F",
  [25] = "CastleOrdeals2F",
  [26] = "CastleOrdeals3F",
  [27] = "MarshCaveB2",
  [28] = "MarshCaveB3",
  [29] = "EarthCaveB2",
  [30] = "EarthCaveB3",
  [31] = "EarthCaveB4",
  [32] = "EarthCaveB5",
  [33] = "GurguVolcanoB2",
  [34] = "GurguVolcanoB3",
  [35] = "GurguVolcanoB4",
  [36] = "GurguVolcanoB5",
  [37] = "IceCaveB2",
  [38] = "IceCaveB3",
  [39] = "BahamutCaveB2",
  [40] = "MirageTower2F",
  [41] = "MirageTower3F",
  [42] = "SeaShrineB5",
  [43] = "SeaShrineB4",
  [44] = "SeaShrineB3",
  [45] = "SeaShrineB2",
  [46] = "SeaShrineB1",
  [47] = "SkyPalace1F",
  [48] = "SkyPalace2F",
  [49] = "SkyPalace3F",
  [50] = "SkyPalace4F",
  [51] = "SkyPalace5F",
  [52] = "TempleOfFiendsRevisited1F",
  [53] = "TempleOfFiendsRevisited2F",
  [54] = "TempleOfFiendsRevisited3F",
  [55] = "TempleOfFiendsRevisitedEarth",
  [56] = "TempleOfFiendsRevisitedFire",
  [57] = "TempleOfFiendsRevisitedWater",
  [58] = "TempleOfFiendsRevisitedAir",
  [59] = "TempleOfFiendsRevisitedChaos",
  [60] = "TitansTunnel",
}
