#!/usr/bin/env python3
"""Write scripts/incentive_slots.lua -- every slot a seed's incentive flags speak for.

The gold ring that marks an incentivized slot is set from Lua, one section at a
time, so something has to know which sections those are. That list lives in the
location files already -- as the `^$incentiveSlot|<flag>` terms on the incentive
map, and as the matching `hosted_item` on the real board -- so it is read back
out of them rather than typed a second time and left to drift.

Three files contribute:

  locations/incentives.json           the incentive tab's own pins
  locations/NOverworld/incentives.json  the same tab on the NOverworld art,
                                      which renames several of its nodes
  locations/overworld.json            the same slots where the player actually
                                      walks, on the overworld and dungeon tabs

Only one of the two incentive files is loaded per variant, so a path that does
not resolve at runtime is expected rather than an error -- the pass skips it.

Usage:
    tools/incentive_slots.py            # write the file
    tools/incentive_slots.py --check    # exit 1 if it is out of date
"""

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PACK = os.path.dirname(HERE)

OUT = "scripts/incentive_slots.lua"

INCENTIVE_FILES = ("locations/incentives.json",
                   "locations/NOverworld/incentives.json")
BOARD_FILE = "locations/overworld.json"

TERM = "^$incentiveSlot|"

# cardiaIncentive is hosted by two different slots -- the Cardia forest chest
# and Bahamut's hoard -- gated on two different flags. The hoard names its own
# flag in a visibility rule (it is a map edit, so it is hidden rather than
# demoted when off); everything else takes the base flag.
HOSTED_OVERRIDE = {"cardiaIncentive": "cardiaIsIncentive"}


def sections(tree):
    """(node name, section) for every section in the file."""
    out = []

    def walk(nodes):
        for node in nodes:
            for section in node.get("sections", []):
                out.append((node.get("name"), section))
            walk(node.get("children", []))

    walk(tree)
    return out


def load(rel):
    with open(os.path.join(PACK, rel)) as handle:
        return json.load(handle)


def flag_of(section):
    """The incentive flag a section is spoken for by, or None."""
    for alt in section.get("access_rules") or []:
        if TERM in alt:
            return alt.split(TERM, 1)[1].split(",")[0]
    vis = section.get("visibility_rules") or []
    if len(vis) == 1:
        return vis[0]
    return None


def collect():
    rows = []
    seen = set()
    hosted_flag = {}

    for rel in INCENTIVE_FILES:
        for node, section in sections(load(rel)):
            flag = flag_of(section)
            if not flag:
                continue
            hosted = section.get("hosted_item")
            if hosted:
                hosted_flag.setdefault(hosted, flag)
            path = "@%s/%s" % (node, section["name"])
            if path not in seen:
                seen.add(path)
                rows.append((path, flag))

    for hosted, override in HOSTED_OVERRIDE.items():
        hosted_flag[hosted] = override

    for node, section in sections(load(BOARD_FILE)):
        hosted = section.get("hosted_item")
        if not hosted or hosted not in hosted_flag:
            continue
        # The hoard keeps its own visibility rule on the real board too, and it
        # is the one place the override must not win.
        flag = flag_of(section) or hosted_flag[hosted]
        path = "@%s/%s" % (node, section["name"])
        if path not in seen:
            seen.add(path)
            rows.append((path, flag))

    return rows


def render(rows):
    width = max(len(flag) for _, flag in rows) + 2
    lines = [
        "-- Generated by tools/incentive_slots.py. Do not edit by hand.",
        "--",
        "-- Every section a seed's incentive flags speak for, and the flag that",
        "-- speaks for it. scripts/incentives.lua rings the ones a seed kept.",
        "--",
        "-- Both incentive trees are listed and only one loads per variant, so a",
        "-- path that does not resolve is expected rather than an error.",
        "INCENTIVE_SLOTS = {",
    ]
    for path, flag in rows:
        lines.append('  { flag = %-*s path = "%s" },'
                     % (width, '"%s",' % flag, path))
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the generated file is out of date")
    args = ap.parse_args()

    rows = collect()
    text = render(rows)
    path = os.path.join(PACK, OUT)

    if args.check:
        current = open(path).read() if os.path.exists(path) else None
        if current != text:
            print("%s is out of date -- rerun tools/incentive_slots.py" % OUT,
                  file=sys.stderr)
            return 1
        print("%s: %d slots, up to date" % (OUT, len(rows)))
        return 0

    with open(path, "w") as handle:
        handle.write(text)
    print("%s: %d slots" % (OUT, len(rows)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
