#!/usr/bin/env python3
"""Which map each location's pin is drawn on, for scripts/location_maps.lua.

A hint names an Archipelago location and the player has to find it on a board
that calls it something else. Answering "where is it?" needs the map the pin
sits on, and nothing in the pack knows: LOCATION_MAPPING carries a section path
and no map, INCENTIVE_SLOTS carries no map, and a section cannot be asked --
locationsection.cpp's Lua surface offers counts, accessibility and Highlight,
and nothing about where it is drawn.

What does know is the location tree, where a node carries `map_locations` naming
the map its markers go on. This joins that to LOCATION_MAPPING's paths and emits
the table the pack loads.

Committed rather than written by a regen, like scripts/map_names.lua and for the
same reason: which floor a chest is on is not a fact about a seed. What is a
fact about a seed is which tab a map belongs to, and that comes from MAP_VALUE,
which a regen does rewrite -- so tabPathForMap picks the override's tabs up for
free and this table never has to.

    tools/location_maps.py            write the table to stdout
    tools/location_maps.py --check    say whether the committed copy matches
"""

import json
import os
import re
import sys

TOOLS = os.path.dirname(os.path.abspath(__file__))
PACK = os.path.dirname(TOOLS)
sys.path.insert(0, TOOLS)

import render_maps  # noqa: E402
import split_locations  # noqa: E402

OUT = os.path.join(PACK, "scripts", "location_maps.lua")

TREES = (
    "locations/overworld.json",
    "locations/incentives.json",
    "locations/NOverworld/overworld.json",
    "locations/NOverworld/incentives.json",
)

# The overworld poster is a map the cartridge does not have, and ff1/map,
# ff1/edges and MAP_NAMES all already call it -1.
OVERWORLD_ID = -1

# The incentive sheet is not a cartridge map and has no id. Every path it would
# have claimed is in the overworld tree too, carrying a real map, so dropping it
# loses nothing -- and a made-up id here would be a tab this pack cannot open.
NOT_A_MAP = ("incentives",)


def maps_by_node():
    """{location node name: {map name}} across every committed tree.

    A node with no `map_locations` of its own inherits its parent's, which is
    not a convenience: the six overworld NPCs -- Coneria's King and Sara, the
    Elf Prince, Astos, Matoya and the Robot -- have no markers of their own
    because their pin genuinely is the parent's overworld pin.
    """
    found = {}

    def walk(node, inherited):
        if isinstance(node, list):
            for item in node:
                walk(item, inherited)
            return
        if not isinstance(node, dict):
            return
        own = {m.get("map") for m in node.get("map_locations", [])
               if isinstance(m, dict) and m.get("map")}
        here = own or inherited
        name = node.get("name")
        if name and node.get("sections"):
            found.setdefault(name, set()).update(here)
        for child in node.get("children", []) or []:
            walk(child, here)

    for rel in TREES:
        with open(os.path.join(PACK, rel), encoding="utf-8-sig") as fh:
            walk(json.load(fh), set())
    return found


def table():
    """{section path: [map ids]} for every path LOCATION_MAPPING names."""
    ids = {name: i for i, name in render_maps.MAP_FILES.items()}
    ids["overworld"] = OVERWORLD_ID
    nodes = maps_by_node()

    out, unknown, unplaced = {}, set(), []
    for _, (path, _hosted) in sorted(split_locations.load_mapping(limit=None).items()):
        names = nodes.get(split_locations.leaf_of(path), set())
        here = set()
        for name in names:
            if name in NOT_A_MAP:
                continue
            if name not in ids:
                unknown.add(name)
                continue
            here.add(ids[name])
        if here:
            out[path] = sorted(here)
        else:
            unplaced.append(path)
    return out, sorted(unknown), unplaced


def render(rows):
    lines = [
        "-- Which map the pack draws each location's pin on. -1 is the overworld.",
        "--",
        "-- Generated by tools/location_maps.py; tools/tests/test_location_maps.py",
        "-- fails when this copy and that one disagree. Committed rather than",
        "-- written by a regen for the same reason scripts/map_names.lua is: which",
        "-- floor a chest sits on is not a fact about a seed.",
        "--",
        "-- Always a list, including for the 246 locations drawn once, so no reader",
        "-- has to branch on the type. The handful with several are real -- a chest",
        "-- the cartridge lays on more than one floor, and the Temple rows that",
        "-- appear once per ToFR mode.",
        "--",
        "-- The tab comes from scripts/autotracking/mapValues.lua via tabPathForMap,",
        "-- which a regen does rewrite, so an override's own tabs are picked up here",
        "-- for free.",
        "LOCATION_MAPS = {",
    ]
    for path in sorted(rows):
        maps = ", ".join(str(i) for i in rows[path])
        lines.append('  ["%s"] = {%s},' % (path, maps))
    lines.append("}")
    return "\n".join(lines) + "\n"


def parse(src):
    """The committed table, read back the way the drift test compares it."""
    rows = {}
    for path, body in re.findall(r'\["([^"]+)"\] = \{([^}]*)\}', src):
        rows[path] = [int(n) for n in re.findall(r'-?\d+', body)]
    return rows


def main(argv):
    rows, unknown, unplaced = table()
    if unknown:
        print("map names no cartridge map claims: %s" % ", ".join(unknown),
              file=sys.stderr)
        return 2
    if unplaced:
        print("locations no tree places: %s" % ", ".join(unplaced), file=sys.stderr)
        return 2
    text = render(rows)
    if "--check" in argv:
        with open(OUT) as fh:
            have = fh.read()
        if have == text:
            print("scripts/location_maps.lua is current (%d locations)" % len(rows))
            return 0
        print("scripts/location_maps.lua is stale -- rerun tools/location_maps.py",
              file=sys.stderr)
        return 1
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
